In [4]:
class Employee:
    num_employees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.num_employees += 1

    def display_employee_info(self):
        print(f"Name: {self.name}")
        print(f"Family: {self.family}")
        print(f"Salary: ${self.salary}")
        print(f"Department: {self.department}")

    @staticmethod
    def average_salary(employee_list):
        total_salary = sum(emp.salary for emp in employee_list)
        return total_salary / len(employee_list) if len(employee_list) > 0 else 0


class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)


# Create instances of Employee class
employee1 = Employee("Shravya Mendu", "Mendu Family", 70000, "HR")
employee2 = Employee("Sreekanth Reddy", "Reddy Family", 65000, "IT")
employee3 = Employee("Mendu Sai", "Sai Family", 75000, "Finance")

# Create instances of FulltimeEmployee class
fulltime_employee1 = FulltimeEmployee("Sai Prem", "Prem Family", 80000, "Marketing")
fulltime_employee2 = FulltimeEmployee("Dondapati Hruthik", "Hruthik Family", 70000, "Sales")

# Display employee information
employee1.display_employee_info()
print("------------------------")
employee2.display_employee_info()
print("------------------------")
employee3.display_employee_info()
print("------------------------")
fulltime_employee1.display_employee_info()
print("------------------------")
fulltime_employee2.display_employee_info()
print("------------------------")

# Calculate and display average salary
all_employees = [employee1, employee2, employee3, fulltime_employee1, fulltime_employee2]
avg_salary = Employee.average_salary(all_employees)
print(f"Average Salary: ${avg_salary:.2f}")

# Display total number of employees
print(f"Total Number of Employees: {Employee.num_employees}")

Name: Shravya Mendu
Family: Mendu Family
Salary: $70000
Department: HR
------------------------
Name: Sreekanth Reddy
Family: Reddy Family
Salary: $65000
Department: IT
------------------------
Name: Mendu Sai
Family: Sai Family
Salary: $75000
Department: Finance
------------------------
Name: Sai Prem
Family: Prem Family
Salary: $80000
Department: Marketing
------------------------
Name: Dondapati Hruthik
Family: Hruthik Family
Salary: $70000
Department: Sales
------------------------
Average Salary: $72000.00
Total Number of Employees: 5


In [5]:







import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

# Reshape the vector into a 4x5 array
reshaped_array = random_vector.reshape(4, 5)

# Find the indices of the maximum value in each row
max_indices = np.argmax(reshaped_array, axis=1)

# Replace the maximum value in each row with 0
for row_idx, col_idx in enumerate(max_indices):
    reshaped_array[row_idx, col_idx] = 0

print("Original random vector:")
print(random_vector)
print("\nReshaped array:")
print(reshaped_array)

Original random vector:
[ 4.82502281  7.91233256 15.99817744  0.          7.68987985  9.5372914
 10.416637    0.         13.20609747  7.10925214 15.46040703  6.50036468
 10.6571396   0.          8.60048663  7.61309465 16.64008095  0.
 15.03758266 17.87398975]

Reshaped array:
[[ 4.82502281  7.91233256 15.99817744  0.          7.68987985]
 [ 9.5372914  10.416637    0.         13.20609747  7.10925214]
 [15.46040703  6.50036468 10.6571396   0.          8.60048663]
 [ 7.61309465 16.64008095  0.         15.03758266 17.87398975]]
